accounts:
  - name: alice
    coins: ["100000000uatom", "100000000000000000000aechelon"]
  - name: bob
    coins: ["5000000000000aechelon"]
validator:
  name: alice
  staked: "100000000000000000000aechelon"
faucet:
  name: bob 
  coins: ["10aechelon"]
build:
  binary: "echelond"
init:
  home: "$HOME/.echelond"
  app:
    evm-rpc:
      address: "0.0.0.0:8545"     # change the JSON-RPC address and port
      ws-address: "0.0.0.0:8546"  # change the JSON-RPC websocket address and port
genesis:
  chain_id: "echelon_3000-3"
  app_state:
    staking:
      params:
        bond_denom: "aechelon"
    mint:
      params:
        mint_denom: "aechelon"
    crisis:
      constant_fee:
        denom: "aechelon"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "aechelon"
    evm:
      params:
        evm_denom: "aechelon"
